# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_each do |lane, options|
    gradle(task: "clean")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    gradle(task: "bundleRelease")
    upload_to_play_store(track: options[:track], skip_upload_apk: true)
  end
end
